#
# Workflow: Report PR
#

# beware! for workflow_run workflow to run, it must exist on the master or default branch!

name: Report PR
on:
  workflow_run:
    workflows: [ "Build PR" ]
    types:
      - completed

jobs:

  report-pr:

    name: Report PR
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:

      # checkout the hazelcast/hazelcast-csharp-client repository
      # no need for submodules, but we need the .github directory
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false

      - name: Prepare
        shell: bash
        run: |
          echo "Build PR conclusion: ${{ github.event.workflow_run.conclusion }}"
          mkdir ./temp
          mkdir ./temp/test-results
          mkdir ./temp/test-coverage

      # cannot use download action because we get artifacts from another run
      - name: Download tests results and coverage artifacts
        uses: actions/github-script@v4
        with:
          script: |
            var fs = require('fs');
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            async function download(prefix, path) {
              var filtered = artifacts.data.artifacts.filter((x) => {
                return x.name.startsWith(prefix);
              });
              for (const artifact of filtered) {
                var download = await github.actions.downloadArtifact({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   artifact_id: artifact.id,
                   archive_format: 'zip',
                });
                var path2 = path.replace('XXXX', artifact.name.substring(prefix.length));
                await fs.writeFile(process.env.GITHUB_WORKSPACE + path2, Buffer.from(download.data));                
              }
            }
            await download('Test-Results ', '/temp/test-results/test-results-XXXX.zip');
            await download('Test-Coverage ', '/temp/test-coverage/test-coverage-XXXX.zip');

      # unzip artifacts
      - name: Unzip artifacts
        id: unzip
        shell: bash
        run: |
          echo "Tests results:"
          found=0
          for f in temp/test-results/test-results-*.zip;
          do
            found=1
            echo "unzip $f"
            unzip $f -d ${f%/*}
          done
          if [ $found -eq 1]; then
            echo "::set-output name=results::true"
          else
            echo "::set-output name=results::false"
            echo "(missing)"
          fi

          echo "Tests coverage:"
          found=0
          for f in temp/test-results/test-coverage-*.zip;
          do
            found=1
            echo "unzip $f"
            unzip $f -d ${f%.*}
          done
          if [ $found -eq 1]; then
            echo "::set-output name=coverage::true"
          else
            echo "::set-output name=coverage::false"
            echo "(missing)"
          fi

      # report test results
      - name: Report test results
        if: steps.unzip.outputs.results == 'true'
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ./temp/test-results/results-*.trx
          reporter: dotnet-trx
          list-suites: failed
          list-tests: failed
          fail-on-error: false

      # report test coverage
      - name: Report test coverage
        if: steps.unzip.outputs.coverage == 'true'
        uses: ./.github/actions/dotcover-report
        with:
          name: Test Coverage
          path: ./temp/test-coverage/test-coverage-windows-net6.0
          sha: ${{ github.sha }}

      # publish to codecov
      - name: Publish to Codecov
        if: steps.unzip.outputs.coverage == 'true'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./temp/test-coverage/test-coverage-windows-net6.0/cover-net6.0.json